import NativeCarryGeometry.Arithmetic.PositionalDecomposition
import NativeCarryGeometry.Arithmetic.BinaryCenter
import NativeCarryGeometry.Arithmetic.BalancedResidue
import NativeCarryGeometry.Arithmetic.CarryDepth
import NativeCarryGeometry.Measure.CarryMass
import NativeCarryGeometry.Measure.CarryProbability
import NativeCarryGeometry.Measure.QuadraticAmplitude
import NativeCarryGeometry.Operator.RealState
import NativeCarryGeometry.Operator.QuadraticDomain
import NativeCarryGeometry.Bracket.CenteredDifference
import NativeCarryGeometry.Bracket.BalancedCamera
import NativeCarryGeometry.Bracket.RadialCurvature
import NativeCarryGeometry.Operator.FiniteRealOperator
import NativeCarryGeometry.Operator.BoundaryOperator
import NativeCarryGeometry.Operator.ResultantConfinement
import NativeCarryGeometry.Operator.ZeroSetFactorization
import NativeCarryGeometry.Analytic.FiniteBracketChart
import NativeCarryGeometry.Analytic.BracketSeries
import NativeCarryGeometry.Analytic.BracketHolomorphy
import NativeCarryGeometry.Analytic.CanonicalContinuation
import NativeCarryGeometry.Equivalence.ComplexCoordinates
import NativeCarryGeometry.Equivalence.RealAnalyticBoundary

/-!
# Native Carry Geometry

Audit root for the native theory.  The external classical identification is
deliberately absent.
-/
