#!/usr/bin/env python3
"""Generate or verify elaborated theorem signatures and axiom evidence.

``audit/theorems.tsv`` is the human-maintained crosswalk.  Lean remains the
authority for declaration names, types, and transitive axioms.  This script
generates a small driver containing ``#ncg_audit`` commands, runs it through
the pinned toolchain, and turns the emitted records into deterministic audit
artifacts.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from auditlib import (
    AuditFailure,
    NCG_ID_RE,
    REPOSITORY_ROOT,
    fail_if_errors,
    write_report,
)


LEAN_VERSION = "4.32.0"
MATHLIB_COMMIT = "81a5d257c8e410db227a6665ed08f64fea08e997"
SIGNATURE_FORMAT = "ncg-signature-v1"
REGISTRY_PATH = REPOSITORY_ROOT / "audit" / "theorems.tsv"
DRIVER_PATH = (
    REPOSITORY_ROOT
    / "NativeCarryGeometry"
    / "Audit"
    / "ExportTheoremTypes.lean"
)
JSON_REGISTRY_PATH = REPOSITORY_ROOT / "audit" / "theorem-registry.json"
AXIOMS_PATH = REPOSITORY_ROOT / "audit" / "axioms.json"
PREIMAGE_DIRECTORY = REPOSITORY_ROOT / "audit" / "preimages"
AUDIT_PREFIX = "NCG_AUDIT\t"
INACTIVE_STATUSES = {"retired", "reserved"}
ALLOWED_AXIOMS = {"Classical.choice", "Quot.sound", "propext"}


@dataclass
class Table:
    fieldnames: list[str]
    records: list[dict[str, str]]


@dataclass(frozen=True)
class LeanRecord:
    declaration: str
    type_repr: str
    axioms: tuple[str, ...]


def read_table() -> Table:
    if not REGISTRY_PATH.is_file():
        raise AuditFailure("missing audit/theorems.tsv")
    raw = REGISTRY_PATH.read_text(encoding="utf-8")
    reader = csv.DictReader(raw.splitlines(), delimiter="\t")
    if reader.fieldnames is None:
        raise AuditFailure("audit/theorems.tsv has no header")
    required = {"id", "declaration", "module", "type_sha256"}
    missing = sorted(required - set(reader.fieldnames))
    if missing:
        raise AuditFailure(
            "audit/theorems.tsv is missing required columns: " + ", ".join(missing)
        )
    records: list[dict[str, str]] = []
    errors: list[str] = []
    seen_ids: dict[str, int] = {}
    seen_declarations: dict[str, int] = {}
    for line, raw_record in enumerate(reader, start=2):
        if None in raw_record:
            errors.append(f"audit/theorems.tsv:{line}: too many fields")
            continue
        record = {key: (value or "").strip() for key, value in raw_record.items()}
        theorem_id = record["id"]
        if not NCG_ID_RE.fullmatch(theorem_id):
            errors.append(f"audit/theorems.tsv:{line}: invalid ID {theorem_id!r}")
        if not record["declaration"]:
            errors.append(f"audit/theorems.tsv:{line}: missing declaration")
        if theorem_id in seen_ids:
            errors.append(
                f"audit/theorems.tsv:{line}: duplicate ID {theorem_id!r}; "
                f"first seen on line {seen_ids[theorem_id]}"
            )
        else:
            seen_ids[theorem_id] = line
        declaration = record["declaration"]
        if declaration in seen_declarations:
            errors.append(
                f"audit/theorems.tsv:{line}: duplicate declaration "
                f"{declaration!r}; first seen on line "
                f"{seen_declarations[declaration]}"
            )
        else:
            seen_declarations[declaration] = line
        records.append(record)
    fail_if_errors(errors)
    return Table(list(reader.fieldnames), records)


def active_records(table: Table) -> list[dict[str, str]]:
    return [
        record
        for record in table.records
        if record.get("status", "active").lower() not in INACTIVE_STATUSES
    ]


def expected_driver(records: list[dict[str, str]]) -> str:
    lines = [
        "/- This file is generated by scripts/generate_theorem_registry.py. -/",
        "import NativeCarryGeometry",
        "import NativeCarryGeometry.Audit.TheoremId",
        "",
    ]
    for record in records:
        lines.append(f"#ncg_audit {record['declaration']}")
    return "\n".join(lines) + "\n"


def build_audit_command() -> str:
    completed = subprocess.run(
        [
            "lake",
            "build",
            "--wfail",
            "NativeCarryGeometry.Audit.TheoremId",
        ],
        cwd=REPOSITORY_ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="strict",
        check=False,
    )
    if completed.returncode != 0:
        raise AuditFailure(
            "Lean audit command failed to build with exit code "
            f"{completed.returncode}:\n{completed.stdout}"
        )
    return completed.stdout


def run_lean_driver() -> tuple[dict[str, LeanRecord], str]:
    completed = subprocess.run(
        ["lake", "env", "lean", str(DRIVER_PATH.relative_to(REPOSITORY_ROOT))],
        cwd=REPOSITORY_ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="strict",
        check=False,
    )
    output = completed.stdout
    if completed.returncode != 0:
        raise AuditFailure(
            "Lean audit driver failed with exit code "
            f"{completed.returncode}:\n{output}"
        )

    result: dict[str, LeanRecord] = {}
    errors: list[str] = []
    for line in output.splitlines():
        marker = line.find(AUDIT_PREFIX)
        if marker < 0:
            continue
        payload = line[marker:].split("\t", 3)
        if len(payload) != 4 or payload[0] != "NCG_AUDIT":
            errors.append(f"malformed Lean audit record: {line!r}")
            continue
        _, declaration, type_repr, raw_axioms = payload
        axioms = tuple(sorted(item for item in raw_axioms.split(",") if item))
        if declaration in result:
            errors.append(f"duplicate Lean audit output for {declaration}")
            continue
        result[declaration] = LeanRecord(declaration, type_repr, axioms)
    fail_if_errors(errors)
    return result, output


def preimage(record: LeanRecord) -> str:
    return (
        f"format={SIGNATURE_FORMAT}\n"
        f"declaration={record.declaration}\n"
        f"lean={LEAN_VERSION}\n"
        f"mathlib={MATHLIB_COMMIT}\n"
        f"type-repr={record.type_repr}\n"
    )


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def json_text(payload: object) -> str:
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def tsv_text(table: Table) -> str:
    from io import StringIO

    stream = StringIO(newline="")
    writer = csv.DictWriter(
        stream,
        fieldnames=table.fieldnames,
        delimiter="\t",
        lineterminator="\n",
        extrasaction="raise",
    )
    writer.writeheader()
    writer.writerows(table.records)
    return stream.getvalue()


def compare_or_write(path: Path, content: str, write: bool, errors: list[str]) -> None:
    if write:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return
    if not path.is_file():
        errors.append(f"missing generated artifact {path.relative_to(REPOSITORY_ROOT)}")
        return
    observed = path.read_text(encoding="utf-8")
    if observed != content:
        errors.append(
            f"stale generated artifact {path.relative_to(REPOSITORY_ROOT)}; "
            "run scripts/generate_theorem_registry.py --write"
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()

    table = read_table()
    active = active_records(table)
    driver = expected_driver(active)
    errors: list[str] = []
    compare_or_write(DRIVER_PATH, driver, args.write, errors)
    fail_if_errors(errors)

    build_audit_command()
    lean_records, lean_output = run_lean_driver()
    expected_declarations = {record["declaration"] for record in active}
    observed_declarations = set(lean_records)
    for declaration in sorted(expected_declarations - observed_declarations):
        errors.append(f"Lean emitted no audit record for {declaration}")
    for declaration in sorted(observed_declarations - expected_declarations):
        errors.append(f"Lean emitted unexpected audit record for {declaration}")
    fail_if_errors(errors)

    by_declaration = {record["declaration"]: record for record in active}
    preimages: dict[str, str] = {}
    theorem_entries: list[dict[str, object]] = []
    axiom_entries: list[dict[str, object]] = []

    for declaration in sorted(expected_declarations):
        table_record = by_declaration[declaration]
        lean_record = lean_records[declaration]
        theorem_id = table_record["id"]
        signature_preimage = preimage(lean_record)
        signature_digest = digest(signature_preimage)
        table_record["type_sha256"] = signature_digest
        preimages[theorem_id] = signature_preimage

        forbidden_axioms = sorted(
            name
            for name in lean_record.axioms
            if name not in ALLOWED_AXIOMS
        )
        if forbidden_axioms:
            errors.append(
                f"{theorem_id} depends on forbidden axiom(s): "
                + ", ".join(forbidden_axioms)
            )

        entry: dict[str, object] = dict(table_record)
        entry["type_repr"] = lean_record.type_repr
        entry["axioms"] = list(lean_record.axioms)
        theorem_entries.append(entry)
        axiom_entries.append(
            {
                "id": theorem_id,
                "declaration": declaration,
                "axioms": list(lean_record.axioms),
            }
        )

    registry_payload = {
        "schema": "native-carry-theorem-registry-v1",
        "signature_format": SIGNATURE_FORMAT,
        "lean": LEAN_VERSION,
        "mathlib": MATHLIB_COMMIT,
        "theorems": sorted(theorem_entries, key=lambda item: str(item["id"])),
    }
    axioms_payload = {
        "schema": "native-carry-axiom-audit-v1",
        "policy": {
            "forbidden": [
                "Lean sorryAx",
                "any axiom outside the explicit allowlist",
            ],
            "allowed": sorted(ALLOWED_AXIOMS),
            "note": (
                "Only propext, Classical.choice, and Quot.sound are permitted; "
                "every transitive use is recorded per declaration."
            ),
        },
        "theorems": sorted(axiom_entries, key=lambda item: str(item["id"])),
    }

    compare_or_write(
        JSON_REGISTRY_PATH, json_text(registry_payload), args.write, errors
    )
    compare_or_write(AXIOMS_PATH, json_text(axioms_payload), args.write, errors)
    compare_or_write(REGISTRY_PATH, tsv_text(table), args.write, errors)

    expected_preimage_names = {f"{theorem_id}.txt" for theorem_id in preimages}
    if not args.write and not PREIMAGE_DIRECTORY.is_dir():
        errors.append("missing generated artifact directory audit/preimages")
    if PREIMAGE_DIRECTORY.is_dir():
        observed_preimage_names = {
            path.name for path in PREIMAGE_DIRECTORY.glob("*.txt") if path.is_file()
        }
        for extra in sorted(observed_preimage_names - expected_preimage_names):
            errors.append(f"unexpected generated preimage audit/preimages/{extra}")
    for theorem_id, content in sorted(preimages.items()):
        compare_or_write(
            PREIMAGE_DIRECTORY / f"{theorem_id}.txt",
            content,
            args.write,
            errors,
        )

    report_payload = {
        "check": "elaborated-theorem-registry",
        "mode": "write" if args.write else "check",
        "declaration_count": len(active),
        "signature_format": SIGNATURE_FORMAT,
        "lean": LEAN_VERSION,
        "mathlib": MATHLIB_COMMIT,
        "lean_output_sha256": digest(lean_output),
        "errors": sorted(set(errors)),
        "status": "pass" if not errors else "fail",
    }
    write_report(args.report, report_payload)
    fail_if_errors(errors)
    print(
        f"PASS: elaborated and {'wrote' if args.write else 'verified'} "
        f"{len(active)} registered declarations"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (AuditFailure, OSError, subprocess.SubprocessError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1)
